# Generated by Django 3.1.3 on 2021-10-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='course',
        ),
    ]
